---
  # Title: app-ms-dynamics-nav2017-client
  #
  # Author: Luc Rutten
  # Version: 1.0
  #
  # Description: Install MS Dynamics NAV2017 client on Endpoint
  # File: tasks/windows-amd64.yml 


  - name: "Check if package is allready installed before downloading installation files."
    win_reg_stat:
      path: "{{ pkg_reg_uninstall_path_amd64 }}{{ pkg_product_id_amd64 }}"
    register: pkg_isinstalled

  - name: "Create local Ansible repository"
    win_file:
      path: "{{ pkg_local_path }}"
      state: directory
    when:
      - pkg_isinstalled.exists == false

  - name: "Download Package"
    win_get_url:
      url: "{{ pkg_remote_url_amd64 }}"
      dest: "{{ pkg_local_path }}/{{ pkg_name_zip_amd64 }}"
      force: no
    when:
      - pkg_isinstalled.exists == false

  - name: "Unzip package"
    win_unzip:
      src: "{{ pkg_local_path }}/{{ pkg_name_zip_amd64 }}"
      dest: "{{ pkg_local_path }}"
    when:
      - pkg_isinstalled.exists == false

  - name: "Installing {{ pkg_name }} (amd64)"
    win_package:
      path: "{{ pkg_installer_amd64 }}"
      product_id: "{{ pkg_product_id_amd64 }}"
      arguments: "{{ pkg_arguments_amd64 }}"
      state: present
    when:
      - pkg_isinstalled.exists == false

  - name: "Removing installation files"
    win_file:
      path: "{{ pkg_local_path }}"
      state: absent
    when:
      - pkg_isinstalled.exists == false
